### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by nzoschke** [nzoschke/jukelab#33]
Goal is to bring this back up to "party ready" then an official "5.0" launch. Requirements...

App is easy to start, restart and run for hours:

- [ ] iPad or Chromebook device with full screen app
- [ ] Wake lock
- [ ] Queue save and recover

Music engine is rock solid and keep music playing for 5+ hours:

- [x] Spotify Web Playback SDK
- [ ] Token refresh
- [ ] Play test for hours

Music content is fully customizable:

- [ ] Custom playlist
- [ ] Compilation albums

Look and feel is customized for a happy hour:

- [ ] Party skin
- [ ] Physical keyboard (if desired by skin author)

Out of scope:

- Offline mode
